-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 20:36:56 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ligafutboldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ligafutboldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ligafutboldbantigua` DEFAULT CHARACTER SET utf8 ;
USE `ligafutboldbantigua` ;

-- -----------------------------------------------------
-- Table `ligafutboldb`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligafutboldbantigua`.`equipo` (
  `idEquipo` INT NOT NULL,
  `nombreEquipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligafutboldb`.`estadio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligafutboldbantigua`.`estadio` (
  `idEstadio` INT NOT NULL,
  `nombreEstadio` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligafutboldb`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligafutboldbantigua`.`jugador` (
  `idJugador` INT NOT NULL,
  `nombreJugador` VARCHAR(45) NULL,
  `apellidosJugador` VARCHAR(45) NULL,
  `edadJugador` INT(2) NULL,
  `idEquipoJugador` INT(5) NULL,
  PRIMARY KEY (`idJugador`),
  INDEX `idEquipoJugador_idx` (`idEquipoJugador` ASC) VISIBLE,
  CONSTRAINT `idEquipoJugador`
    FOREIGN KEY (`idEquipoJugador`)
    REFERENCES `ligafutboldbantigua`.`equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligafutboldb`.`posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligafutboldbantigua`.`posicion` (
  `idPosicion` INT NOT NULL,
  `nombrePosicion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPosicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligafutboldb`.`jugador_posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligafutboldbantigua`.`jugador_posicion` (
  `idJugador` INT NOT NULL,
  `idPosicion` INT NOT NULL,
  PRIMARY KEY (`idJugador`, `idPosicion`),
  INDEX `idPosicion_idx` (`idPosicion` ASC) VISIBLE,
  CONSTRAINT `idPosicion`
    FOREIGN KEY (`idPosicion`)
    REFERENCES `ligafutboldbantigua`.`posicion` (`idPosicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idJugador`
    FOREIGN KEY (`idJugador`)
    REFERENCES `ligafutboldbantigua`.`jugador` (`idJugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ligafutboldb`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ligafutboldbantigua`.`partido` (
  `idPartido` INT NOT NULL,
  `fecha` DATE NULL,
  `estadioPartido` INT NULL,
  `equipoLocalPartido` INT NULL,
  `equipoVisitantePartido` INT NULL,
  `golesLocalPartido` INT NULL,
  `golesVisitantes` INT NULL,
  PRIMARY KEY (`idPartido`),
  INDEX `equipoVisitantePartido_idx` (`equipoVisitantePartido` ASC) VISIBLE,
  INDEX `estadioPartido_idx` (`estadioPartido` ASC) VISIBLE,
  INDEX `equipoLocalPartido_idx` (`equipoLocalPartido` ASC) VISIBLE,
  CONSTRAINT `equipoLocalPartido`
    FOREIGN KEY (`equipoLocalPartido`)
    REFERENCES `ligafutboldbantigua`.`equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipoVisitantePartido`
    FOREIGN KEY (`equipoVisitantePartido`)
    REFERENCES `ligafutboldbantigua`.`equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estadioPartido`
    FOREIGN KEY (`estadioPartido`)
    REFERENCES `ligafutboldbantigua`.`estadio` (`idEstadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
